window.DAURA_MENU = [
['Soft Drinks','Coke',80],['Soft Drinks','Sprite',80],['Soft Drinks','Redbull',130],['Soft Drinks','Badam Juice',130],['Soft Drinks','Real Juice',130],
['Tea','Milk Tea',30],['Tea','Black Tea',25],['Tea','Lemon Tea',35],['Tea','Green Tea',50],['Tea','Masala Tea',60],['Tea','Hot Lemon Honey',100],['Tea','Hot Lemon Honey with Ginger',120],
['Soup','Chicken Soup',180],['Soup','Mushroom Soup',160],['Soup','Mix Veg Soup',140],['Salad','Nepali Salad',130],['Salad','Fruit Salad',180],
['Snack Veg','Bhatmas Sadeko',150],['Snack Veg','Peanut Sadeko',150],['Snack Veg','Roasted Kaju',310],['Snack Veg','Roasted Papad',40],['Snack Veg','Masala Papad',100],['Snack Veg','Wai-Wai Sadeko',110],['Snack Veg','French Fry',130],['Snack Veg','French Fry Chilli',220],['Snack Veg','Sweet Corn Salad',220],['Snack Veg','Corn Salt & Pepper',250],['Snack Veg','Crispy Corn',280],['Snack Veg','Paneer Chilli',350],['Snack Veg','Paneer Pakauda',400],['Snack Veg','Mushroom Chilli',350],
['Snack Non-Veg','Chicken Lolipop (6 pcs)',350],['Snack Non-Veg','Chicken Chilli',320],['Snack Non-Veg','Chicken Tass',380],['Snack Non-Veg','Chicken Drumstick',370],['Snack Non-Veg','Chicken Sadeko',340],['Snack Non-Veg','Chicken Tikka',480],['Snack Non-Veg','Mutton Sadeko',440],['Snack Non-Veg','Mutton Bhutan',450],['Snack Non-Veg','Mutton Tass',480],
['Momo','Veg Momo - Steam',140],['Momo','Veg Momo - Fried',160],['Momo','Veg Momo - Jhol',180],['Momo','Veg Momo - Chilli',200],['Momo','Chicken Momo - Steam',180],['Momo','Chicken Momo - Fried',200],['Momo','Chicken Momo - Jhol',220],['Momo','Chicken Momo - Chilli',240],['Momo','Mutton Momo - Steam',280],['Momo','Mutton Momo - Fried',300],['Momo','Mutton Momo - Jhol',320],['Momo','Mutton Momo - Chilli',340],
['Chowmin / Noodles','Veg Chowmin',170],['Chowmin / Noodles','Egg Chowmin',220],['Chowmin / Noodles','Chicken Chowmin',240],['Chowmin / Noodles','Paneer Chowmin',280],['Chowmin / Noodles','Mutton Chowmin',320],
['Grilled','Grilled Chicken Leg (2 pcs)',700],['Grilled','Mutton Sekuwa 250g',450],['Grilled','Mutton Sekuwa 500g',900],['Grilled','Mutton Sekuwa 1kg',1800],['Grilled','Chicken Sekuwa 250g',250],['Grilled','Chicken Sekuwa 500g',500],['Grilled','Chicken Sekuwa 1kg',1000],['Grilled','Chicken Wings 250g',300],['Grilled','Chicken Wings 500g',600],['Grilled','Chicken Wings 1kg',1200],
['Curry','Chicken Curry',380],['Curry','Chicken Kadai',400],['Curry','Chicken Masala',400],['Curry','Chicken Butter Masala',450],['Curry','Mutton Curry',500],['Curry','Mutton Kadai',520],['Curry','Mutton Masala',550],['Curry','Mix Veg Curry',320],['Curry','Mix Veg Gravy',320],['Curry','Mix Veg Kadai',350],['Curry','Paneer Kadai',450],['Curry','Panner Butter Masala',460],['Curry','Paneer Tikka Masala',460],['Curry','Dal Fry',170],['Curry','Dal Tadka',190],
['Fried Rice','Veg Fried Rice',180],['Fried Rice','Egg Fried Rice',220],['Fried Rice','Chicken Fried Rice',260],['Fried Rice','Paneer Fried Rice',300],['Fried Rice','Mutton Fried Rice',320],
['Pizza','Veg Pizza',470],['Pizza','Chicken Pizza',550],['Pizza','Paneer Pizza',620],['Pizza','Mutton Pizza',650],
['Briyani','Mix Veg Bariyani',380],['Briyani','Chicken Briyani',470],['Briyani','Mutton Briyani',560],['Briyani','Plain Rice',140],['Briyani','Jeera Rice',160],
['Khana Set','Veg Khana',200],['Khana Set','Chicken Khana',350],['Khana Set','Mutton Khana',450],['Khana Set','Nepali Dhido Set',350],
['Roti / Naan','Plain Roti',30],['Roti / Naan','Butter Roti',40],['Roti / Naan','Plain Naan',60],['Roti / Naan','Butter Naan',80],['Roti / Naan','Garlic Naan',110]
];
