-- Daura Online Ordering Pro V3 - Supabase setup
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text not null,
  phone text not null,
  order_type text not null default 'Delivery' check (order_type in ('Delivery','Pickup')),
  address text,
  payment_method text not null default 'Cash on Delivery',
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0,
  special_instructions text,
  status text not null default 'New' check (status in ('New','Accepted','Preparing','Ready','Delivered'))
);
alter table public.orders enable row level security;
drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders" on public.orders for insert to anon, authenticated
with check (customer_name is not null and length(trim(customer_name)) > 0 and phone is not null and length(trim(phone)) > 0 and jsonb_typeof(items) = 'array' and total >= 0);
drop policy if exists "Admins can view orders" on public.orders;
create policy "Admins can view orders" on public.orders for select to authenticated using (true);
drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders" on public.orders for update to authenticated using (true) with check (true);
grant usage on schema public to anon, authenticated;
grant insert on public.orders to anon, authenticated;
grant select, update on public.orders to authenticated;
grant usage, select on sequence public.orders_id_seq to anon, authenticated;
