-- Daura Online Ordering Pro V3 - Supabase setup
-- Run this in the Supabase SQL Editor once.
-- The customer website inserts with the publishable key as the anon role.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text not null,
  customer_phone text not null,
  order_type text not null default 'Delivery' check (order_type in ('Delivery','Pickup')),
  address text,
  payment_method text not null default 'Cash on Delivery',
  items jsonb not null default '[]'::jsonb,
  total_amount numeric(12,2) not null default 0,
  special_instructions text,
  status text not null default 'pending'
);

-- If an older orders table already exists, add/rename the columns expected by the app.
alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists total_amount numeric(12,2);
alter table public.orders add column if not exists status text;
alter table public.orders add column if not exists special_instructions text;

-- Copy data from the old column names when upgrading an existing table.
-- These statements are guarded by checking whether the legacy columns exist.
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='phone') then
    execute 'update public.orders set customer_phone = phone where customer_phone is null';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='total') then
    execute 'update public.orders set total_amount = total where total_amount is null';
  end if;
end $$;

alter table public.orders alter column items set default '[]'::jsonb;
alter table public.orders alter column status set default 'pending';

-- The previous status CHECK allowed only capitalized workflow states and rejected
-- the website's initial 'pending' value. Remove that old constraint if present.
do $$
declare r record;
begin
  for r in
    select conname
    from pg_constraint
    where conrelid = 'public.orders'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%status%'
  loop
    execute format('alter table public.orders drop constraint %I', r.conname);
  end loop;
end $$;

alter table public.orders add constraint orders_status_check
  check (status in ('pending','New','Accepted','Preparing','Ready','Delivered'));

alter table public.orders enable row level security;

drop policy if exists "Public can create orders" on public.orders;
drop policy if exists "orders_anon_insert" on public.orders;
drop policy if exists "Admins can view orders" on public.orders;
drop policy if exists "Admins can update orders" on public.orders;

create policy "Public can create orders"
on public.orders
for insert to anon, authenticated
with check (
  customer_name is not null
  and length(trim(customer_name)) > 0
  and customer_phone is not null
  and length(trim(customer_phone)) > 0
  and jsonb_typeof(items) = 'array'
  and total_amount >= 0
);

-- Keep admin access available for authenticated admin users.
create policy "Admins can view orders"
on public.orders
for select to authenticated
using (true);

create policy "Admins can update orders"
on public.orders
for update to authenticated
using (true)
with check (true);

-- Explicit Data API grants are required on projects where automatic exposure
-- of new public tables is disabled.
grant usage on schema public to anon, authenticated;
grant insert on public.orders to anon, authenticated;
grant select, update on public.orders to authenticated;

do $$
begin
  if exists (select 1 from pg_class where relkind='S' and relname='orders_id_seq') then
    execute 'grant usage, select on sequence public.orders_id_seq to anon, authenticated';
  end if;
end $$;
